cicd - update apply patches to handle excpetions

diff --git a/.github/workflows/0.7.0_mono_prepare_validate_publish.yaml b/.github/workflows/0.7.0_mono_prepare_validate_publish.yaml
--- a/.github/workflows/0.7.0_mono_prepare_validate_publish.yaml
+++ b/.github/workflows/0.7.0_mono_prepare_validate_publish.yaml
@@ -190,7 +190,7 @@ jobs:
         run: |
           find patches -type f -name "*.patch" | while read patch; do
             echo "Applying patch $patch"
-            git apply -p1 "$patch"
+            git apply -p1 "$patch" || echo "Warning: Patch $patch failed, continuing..."
           done
           rm -rf patches
 
